#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : direwolf
Version  : 1.4
Release  : 1
URL      : https://github.com/wb2osz/direwolf/archive/1.4.tar.gz
Source0  : https://github.com/wb2osz/direwolf/archive/1.4.tar.gz
Summary  : Soundcard based AX.25 TNC
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: direwolf-bin
Requires: direwolf-data
Requires: direwolf-license
Requires: direwolf-man
BuildRequires : alsa-lib-dev
Patch1: 0001-Fix-installation-destinations.patch

%description
Dire Wolf is a software "soundcard" modem/TNC and APRS encoder/decoder.   It can 
be used stand-alone to receive APRS messages, as a digipeater, APRStt gateway, 
or Internet Gateway (IGate).    It can also be used as a virtual TNC for other 
applications such as APRSIS32, UI-View32, Xastir, APRS-TW, YAAC, UISS, 
Linux AX25, SARTrack, RMS Express, and many others.

%package bin
Summary: bin components for the direwolf package.
Group: Binaries
Requires: direwolf-data
Requires: direwolf-license
Requires: direwolf-man

%description bin
bin components for the direwolf package.


%package data
Summary: data components for the direwolf package.
Group: Data

%description data
data components for the direwolf package.


%package doc
Summary: doc components for the direwolf package.
Group: Documentation
Requires: direwolf-man

%description doc
doc components for the direwolf package.


%package license
Summary: license components for the direwolf package.
Group: Default

%description license
license components for the direwolf package.


%package man
Summary: man components for the direwolf package.
Group: Default

%description man
man components for the direwolf package.


%prep
%setup -q -n direwolf-1.4
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535575857
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1535575857
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/direwolf
cp LICENSE-dire-wolf.txt %{buildroot}/usr/share/doc/direwolf/LICENSE-dire-wolf.txt
cp regex/COPYING %{buildroot}/usr/share/doc/direwolf/regex_COPYING
%make_install INSTALLDIR='$(DESTDIR)/usr'

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/aclients
/usr/bin/atest
/usr/bin/decode_aprs
/usr/bin/direwolf
/usr/bin/dwespeak.sh
/usr/bin/gen_packets
/usr/bin/ll2utm
/usr/bin/log2gpx
/usr/bin/telem-balloon.pl
/usr/bin/telem-bits.pl
/usr/bin/telem-data.pl
/usr/bin/telem-data91.pl
/usr/bin/telem-eqns.pl
/usr/bin/telem-parm.pl
/usr/bin/telem-seq.sh
/usr/bin/telem-unit.pl
/usr/bin/telem-volts.py
/usr/bin/text2tt
/usr/bin/tt2text
/usr/bin/ttcalc
/usr/bin/utm2ll

%files data
%defattr(-,root,root,-)
/usr/share/applications/direwolf.desktop
/usr/share/direwolf/dw-icon.png
/usr/share/direwolf/symbols-new.txt
/usr/share/direwolf/symbolsX.txt
/usr/share/direwolf/tocalls.txt

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/direwolf/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/direwolf/LICENSE-dire-wolf.txt
/usr/share/doc/direwolf/LICENSE-other.txt
/usr/share/doc/direwolf/regex_COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/aclients.1
/usr/share/man/man1/atest.1
/usr/share/man/man1/decode_aprs.1
/usr/share/man/man1/direwolf.1
/usr/share/man/man1/gen_packets.1
/usr/share/man/man1/ll2utm.1
/usr/share/man/man1/log2gpx.1
/usr/share/man/man1/text2tt.1
/usr/share/man/man1/tt2text.1
/usr/share/man/man1/utm2ll.1
